export const GET_USER_INFO = 'USER/GET_USER_INFO';
export const GET_USER_RESOLVED = 'USER/GET_USER_RESOLVED';
export const GET_USER_REJECTED = 'USER/GET_USER_REJECTED';

export const LOGIN_REQUEST = 'USER/LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'USER/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USER/LOGIN_FAILURE';
